### ISSUE TITLE
error trying to run script

### ISSUE THREAD

**Issue by lanz** [somada141/matchbook#1]
Trying to run this with Python 3:

$ matchbook.py search isbn Archeofuturism\ by\ Guillame\ Faye.pdf
Traceback (most recent call last):
  File "C:/Users/Lanz/bin/matchbook.py", line 61, in <module>
    @begin.start
  File "C:\Users\Lanz\AppData\Local\Programs\Python\Python37-32\lib\site-packages\begin\main.py", line 135, in start
    return _start(func)
  File "C:\Users\Lanz\AppData\Local\Programs\Python\Python37-32\lib\site-packages\begin\main.py", line 115, in _start
    prog.start()
  File "C:\Users\Lanz\AppData\Local\Programs\Python\Python37-32\lib\site-packages\begin\main.py", line 54, in start
    collector=self._collector)
  File "C:\Users\Lanz\AppData\Local\Programs\Python\Python37-32\lib\site-packages\begin\cmdline.py", line 258, in apply_options
    return_value = call_function(subfunc, signature(subfunc), opts)
  File "C:\Users\Lanz\AppData\Local\Programs\Python\Python37-32\lib\site-packages\begin\cmdline.py", line 236, in call_function
    return func(*pargs, **kwargs)
  File "C:\Users\Lanz\AppData\Local\Programs\Python\Python37-32\lib\site-packages\begin\convert.py", line 92, in wrapper
    return func(*args, **kwargs)
  File "C:/Users/Lanz/bin/matchbook.py", line 50, in search
    raise ValueError("An API key needs to be defined under `api_key` to use the `ISBNdb` corpus.")
ValueError: An API key needs to be defined under `api_key` to use the `ISBNdb` corpus.

**Comment by somada141** [comment]
hey @lanz haven't touched this in forever, lemme see what's going on with it but it seems to be looking for the API key.

**Comment by somada141** [comment]
righto it seems you're invoking it wrong, if you're trying to extract the ISBN from a PDF the syntax is 

```
python matchbook.py isbn path-to.pdf
```

The invocation you used is to identify a given ISBN for which you need to pass an API key.

**Comment by lanz** [comment]
Thanks for responding! You're right, I was invoking the command wrong. Here's what I got now:

$ python matchbook.py isbn Archeofuturism\ by\ Guillame\ Faye.pdf
Traceback (most recent call last):
  File "matchbook.py", line 9, in <module>
    import extractors
  File "C:\Users\Lanz\Desktop\PDFs\extractors.py", line 7, in <module>
    import pdf
  File "C:\Users\Lanz\Desktop\PDFs\pdf.py", line 5, in <module>
    import cStringIO
ModuleNotFoundError: No module named 'cStringIO'

I think this one is due to me using Python 3 and there were some changes with StringIO in version 3.

**Comment by somada141** [comment]
right you are, hadn't updated this to work in Py3. Just pushed a commit with new dependencies and new code that appears to work well. Give it a whirl :).

**Comment by lanz** [comment]
Just tested the update and it works perfectly. This matchbook project is a lifesaver for me, I'm going to use it to help rename 10k+ PDFs. Thank you!
